# Взять официальный базовый образ Python платформы Docker
FROM python:3.12.4

# Задать перемнные среды
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Задать рабочий каталог
WORKDIR /code

# Установить зависимости
RUN pip install --upgrade pip