# Generated by Django 5.1.1 on 2024-09-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("courses", "0004_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="text",
            name="file",
        ),
        migrations.AddField(
            model_name="text",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("text", "video", "image", "file")},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(upload_to="images"),
        ),
    ]
